name: Triggers
run-name: Aprendiendo triggers
on:
  push:
  #  branches:
  #    - master
  #pull_request:
  #  types: [opened, synchronize, reopened]
  #  paths:
  #    - '**.py'
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        type: string
        default: Gollum
jobs:
  Learning-GA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environmen
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: run-script
        run: python hola_mundo.py
